"""Add MoMo import fields

Revision ID: 88e0f97a4f92
Revises: 
Create Date: 2025-11-21 01:34:05.262767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e0f97a4f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counterparty', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('balance_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fees', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('notes')
        batch_op.drop_column('reference')
        batch_op.drop_column('tax')
        batch_op.drop_column('fees')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('counterparty')

    # ### end Alembic commands ###
